server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: "test"
server:
  port: 4000
welcomeMsg: "Welcome from test"
---
spring:
  config:
    activate:
      on-profile: "prod"
server:
  port: 5000
welcomeMsg: "Welcome from prod"
